# Subseting

In [157]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


Matrix of random 2-digit numbers
--------------------------------
 [[92 22 93 19 15]
 [84 82 21 82 44]
 [48 69 69 60 39]]


In [158]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [92 93 84 82 82 69 69 60]


# Slicing

In [159]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [161]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [163]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [164]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [165]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [166]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [167]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [168]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [169]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[6 9 9]
 [2 2 7]
 [8 7 3]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[7 5 2]
 [1 9 9]
 [1 6 5]]


In [170]:
print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)



Addition
------------------
 [[13 14 11]
 [ 3 11 16]
 [ 9 13  8]]

Multiplication
------------------
 [[42 45 18]
 [ 2 18 63]
 [ 8 42 15]]


In [171]:
print("\nDivision\n------------------\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[ 0.85714286  1.8         4.5       ]
 [ 2.          0.22222222  0.77777778]
 [ 8.          1.16666667  0.6       ]]

Lineaer combination: 3*A - 2*B
-----------------------------
 [[  4  17  23]
 [  4 -12   3]
 [ 22   9  -1]]


In [172]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[106 109 109]
 [102 102 107]
 [108 107 103]]


In [173]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


Exponentiation, matrix cubed here
----------------------------------------
 [[216 729 729]
 [  8   8 343]
 [512 343  27]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 2.44948974  3.          3.        ]
 [ 1.41421356  1.41421356  2.64575131]
 [ 2.82842712  2.64575131  1.73205081]]
