In [3]:
import numpy as np

In [2]:
a = np.zeros((10, 2))

In [4]:
# A transpose makes the array non-contiguous

In [5]:
b = a.T

In [6]:
c = b.view()

In [7]:
c.shape = (20)

AttributeError: incompatible shape for a non-contiguous array

In [8]:
#It is not always possible to change the shape of an array without copying the data. 
#If you want an error to be raised when the data is copied, you should assign the new shape to the
#shape attribute of the array

In [10]:
#The order keyword gives the index ordering both for fetching the values from a, and then placing the values 
#into the output array

In [11]:
a = np.arange(6).reshape((3, 2))

In [12]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
#reshaping as first raveling the array
#then inserting the elements from the raveled array into the new array using the same kind of index ordering

In [14]:
np.reshape(np.ravel(a), (2, 3)) # equivalent to C ravel then C reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
np.reshape(a, (2, 3), order='F') # Fortran-like index ordering

array([[0, 4, 3],
       [2, 1, 5]])

In [16]:
np.reshape(np.ravel(a, order='F'), (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [18]:
#examples
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [20]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [21]:
np.reshape(a, (3,-1))       # the unspecified value is inferred to be 2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
 x = np.array([[1, 2, 3], [4, 5, 6]])

In [23]:
print(np.ravel(x))

[1 2 3 4 5 6]


In [24]:
print(x.reshape(-1))

[1 2 3 4 5 6]


In [25]:
print(np.ravel(x, order='F'))

[1 4 2 5 3 6]


In [26]:
#When order is ‘A’, it will preserve the array’s ‘C’ or ‘F’ ordering

In [27]:
print(np.ravel(x.T))

[1 4 2 5 3 6]


In [28]:
print(np.ravel(x.T, order='A'))

[1 2 3 4 5 6]


In [29]:
#When order is ‘K’, it will preserve orderings that are neither ‘C’ nor ‘F’, but won’t reverse axes

In [30]:
a = np.arange(3)[::-1]; a

array([2, 1, 0])

In [31]:
a.ravel(order='C')

array([2, 1, 0])

In [32]:
a.ravel(order='K')

array([2, 1, 0])

In [33]:
a = np.arange(12).reshape(2,3,2).swapaxes(1,2); a

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [34]:
a.ravel(order='C')

array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])

In [35]:
a.ravel(order='K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
#transpose:Permute the dimensions of an array.
#swapaxes:Interchange two axes of an array.

In [37]:
x = np.zeros((3, 4, 5))

In [38]:
np.moveaxis(x, 0, -1).shape

(4, 5, 3)

In [39]:
np.moveaxis(x, -1, 0).shape

(5, 3, 4)

In [40]:
 np.transpose(x).shape

(5, 4, 3)

In [41]:
np.swapaxes(x, 0, -1).shape

(5, 4, 3)

In [42]:
np.moveaxis(x, [0, 1], [-1, -2]).shape

(5, 4, 3)

In [43]:
np.moveaxis(x, [0, 1, 2], [-1, -2, -3]).shape

(5, 4, 3)

In [44]:
x = np.arange(4).reshape((2,2))

In [45]:
x

array([[0, 1],
       [2, 3]])

In [46]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [47]:
x

array([[0, 1],
       [2, 3]])

In [48]:
 x = np.ones((1, 2, 3))

In [49]:
np.transpose(x, (1, 0, 2)).shape

(2, 1, 3)

In [50]:
#Convert inputs to arrays with at least one dimension.

In [51]:
x = np.arange(9.0).reshape(3,3)

In [52]:
np.atleast_1d(x)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [53]:
np.atleast_1d(x) is x

True

In [54]:
np.atleast_1d(1, [3, 4])

[array([1]), array([3, 4])]

In [55]:
#View inputs as arrays with at least two dimensions.

In [56]:
np.atleast_2d(3.0)

array([[ 3.]])

In [57]:
x = np.arange(3.0)

In [58]:
np.atleast_2d(x)

array([[ 0.,  1.,  2.]])

In [59]:
np.atleast_2d(x).base is x

True

In [60]:
np.atleast_2d(1, [1, 2], [[1, 2]])

[array([[1]]), array([[1, 2]]), array([[1, 2]])]

In [61]:
#View inputs as arrays with at least three dimensions.

In [62]:
x = np.arange(12.0).reshape(4,3)

In [63]:
x

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.]])

In [64]:
np.atleast_3d(x).shape

(4, 3, 1)

In [65]:
np.atleast_3d(x).base is x.base

True

In [66]:
for arr in np.atleast_3d([1, 2], [[1, 2]], [[[1, 2]]]):
...     print(arr, arr.shape)

[[[1]
  [2]]] (1, 2, 1)
[[[1]
  [2]]] (1, 2, 1)
[[[1 2]]] (1, 1, 2)


In [67]:
#Broadcast an array to a new shape, a very meaningful feature

In [106]:
x = np.array([1, 2, 3])

In [107]:
x

array([1, 2, 3])

In [108]:
np.broadcast_to(x, (3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [103]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.broadcast_to(x, (13, len(x)))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [109]:
#Broadcast any number of arrays against each other

In [110]:
x = np.array([[1,2,3]])

In [111]:
x

array([[1, 2, 3]])

In [112]:
y = np.array([[1],[2],[3]])

In [113]:
y

array([[1],
       [2],
       [3]])

In [114]:
np.broadcast_arrays(x, y)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])]

In [115]:
[np.array(a) for a in np.broadcast_arrays(x, y)]

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])]

In [116]:
#Expand the shape of an array.

In [117]:
x = np.array([1,2])

In [118]:
x

array([1, 2])

In [119]:
x.shape

(2,)

In [120]:
y = np.expand_dims(x, axis=0)

In [121]:
y

array([[1, 2]])

In [122]:
y.shape

(1, 2)

In [123]:
y = np.expand_dims(x, axis=1)  # Equivalent to x[:,np.newaxis]

In [124]:
y

array([[1],
       [2]])

In [125]:
y.shape

(2, 1)

In [126]:
np.newaxis is None

True

In [127]:
#Remove single-dimensional entries from the shape of an array

In [128]:
x = np.array([[[0], [1], [2]]])

In [129]:
x

array([[[0],
        [1],
        [2]]])

In [130]:
x.shape

(1, 3, 1)

In [131]:
np.squeeze(x).shape

(3,)

In [132]:
np.squeeze(x, axis=0).shape

(3, 1)

In [133]:
np.squeeze(x, axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [134]:
np.squeeze(x, axis=2).shape

(1, 3)

In [135]:
#Return an array converted to a float type

In [136]:
np.asfarray([2, 3])

array([ 2.,  3.])

In [137]:
np.asfarray([2, 3], dtype='float')

array([ 2.,  3.])

In [138]:
np.asfarray([2, 3], dtype='int8')

array([ 2.,  3.])

In [139]:
#Join a sequence of arrays along an existing axis

In [140]:
a = np.array([[1, 2], [3, 4]])

In [141]:
a

array([[1, 2],
       [3, 4]])

In [142]:
b = np.array([[5, 6]])

In [143]:
b

array([[5, 6]])

In [144]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [145]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [146]:
a = np.ma.arange(3)

In [147]:
a

masked_array(data = [0 1 2],
             mask = False,
       fill_value = 999999)

In [148]:
a[1] = np.ma.masked

In [149]:
a

masked_array(data = [0 -- 2],
             mask = [False  True False],
       fill_value = 999999)

In [150]:
b = np.arange(2, 5)

In [151]:
b

array([2, 3, 4])

In [152]:
np.concatenate([a, b])

masked_array(data = [0 1 2 2 3 4],
             mask = False,
       fill_value = 999999)

In [153]:
np.ma.concatenate([a, b])

masked_array(data = [0 -- 2 2 3 4],
             mask = [False  True False False False False],
       fill_value = 999999)

In [154]:
#Join a sequence of arrays along a new axis

In [155]:
[np.random.randn(3, 4) for _ in range(10)]

[array([[ 0.14554751, -0.60835635, -0.02990939, -0.92486407],
        [-0.11223634,  0.3997614 ,  1.27141229,  0.63142596],
        [-1.18113453,  1.0260625 ,  0.79319697, -0.71844249]]),
 array([[ 1.17925871, -2.53683011, -0.26032998, -0.51457485],
        [ 0.58968602,  1.11727461,  0.76267513, -0.35389428],
        [ 1.00501409,  0.95427581, -2.42096073, -1.16218212]]),
 array([[ 0.12137246,  0.31806138, -0.15418759, -1.38144201],
        [ 1.5455355 , -0.39448997, -0.67849026,  0.46412834],
        [-1.0022328 ,  0.98190205,  1.44751215,  0.04053402]]),
 array([[-1.63235288,  1.10241399, -0.70186032,  0.47461136],
        [-0.63219694, -1.43260066,  0.72321198,  0.4280372 ],
        [ 0.04226522,  0.76104497, -1.83221429, -0.77756847]]),
 array([[-1.59873979,  0.13900847,  1.67323645, -1.45090032],
        [ 0.54050572,  0.09143111,  0.19695267,  0.71489649],
        [ 0.24665063,  0.06607317,  1.40603306, -2.07246284]]),
 array([[-0.49801507, -1.68675594,  0.5846229 ,  0.33812499]

In [156]:
arrays = [np.random.randn(3, 4) for _ in range(10)]

In [157]:
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [158]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [159]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [160]:
a = np.array([1, 2, 3])

In [161]:
a

array([1, 2, 3])

In [162]:
b = np.array([2, 3, 4])

In [163]:
b

array([2, 3, 4])

In [164]:
np.stack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [165]:
np.stack((a, b), axis=-1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [166]:
np.column_stack((a,b)) #column stack

array([[1, 2],
       [2, 3],
       [3, 4]])

In [167]:
np.dstack((a,b)) #depthwise stack

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [168]:
np.hstack((a,b)) #horizontal stack

array([1, 2, 3, 2, 3, 4])

In [169]:
np.vstack((a,b)) #vertical stacking

array([[1, 2, 3],
       [2, 3, 4]])

In [170]:
# split an array multiple sub-arrays

In [173]:
x = np.arange(12.0)

In [174]:
x

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.])

In [175]:
np.split(x, [3, 5, 6, 10])

[array([ 0.,  1.,  2.]),
 array([ 3.,  4.]),
 array([ 5.]),
 array([ 6.,  7.,  8.,  9.]),
 array([ 10.,  11.])]

In [176]:
np.split(x, [3, 5, 8, 10, 12])

[array([ 0.,  1.,  2.]),
 array([ 3.,  4.]),
 array([ 5.,  6.,  7.]),
 array([ 8.,  9.]),
 array([ 10.,  11.]),
 array([], dtype=float64)]

In [177]:
np.split(x,[5])

[array([ 0.,  1.,  2.,  3.,  4.]),
 array([  5.,   6.,   7.,   8.,   9.,  10.,  11.])]

In [178]:
np.array_split(x,[5])

[array([ 0.,  1.,  2.,  3.,  4.]),
 array([  5.,   6.,   7.,   8.,   9.,  10.,  11.])]

In [179]:
x = np.arange(16.0).reshape(2, 2, 4)

In [180]:
x

array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.]]])

In [181]:
#multiple splits based on 3rd axis

In [182]:
x = np.arange(16.0).reshape(2, 2, 4)

In [183]:
x

array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.]]])

In [184]:
np.dsplit(x, 2)

[array([[[  0.,   1.],
         [  4.,   5.]],
 
        [[  8.,   9.],
         [ 12.,  13.]]]), array([[[  2.,   3.],
         [  6.,   7.]],
 
        [[ 10.,  11.],
         [ 14.,  15.]]])]

In [185]:
np.dsplit(x, np.array([3, 6]))

[array([[[  0.,   1.,   2.],
         [  4.,   5.,   6.]],
 
        [[  8.,   9.,  10.],
         [ 12.,  13.,  14.]]]), array([[[  3.],
         [  7.]],
 
        [[ 11.],
         [ 15.]]]), array([], shape=(2, 2, 0), dtype=float64)]

In [186]:
np.hsplit(x, 2)

[array([[[  0.,   1.,   2.,   3.]],
 
        [[  8.,   9.,  10.,  11.]]]), array([[[  4.,   5.,   6.,   7.]],
 
        [[ 12.,  13.,  14.,  15.]]])]

In [187]:
np.hsplit(x, np.array([3, 6]))

[array([[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.]],
 
        [[  8.,   9.,  10.,  11.],
         [ 12.,  13.,  14.,  15.]]]),
 array([], shape=(2, 0, 4), dtype=float64),
 array([], shape=(2, 0, 4), dtype=float64)]

In [188]:
np.hsplit(x, 2)

[array([[[  0.,   1.,   2.,   3.]],
 
        [[  8.,   9.,  10.,  11.]]]), array([[[  4.,   5.,   6.,   7.]],
 
        [[ 12.,  13.,  14.,  15.]]])]

In [189]:
np.vsplit(x, 2)

[array([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.]]]), array([[[  8.,   9.,  10.,  11.],
         [ 12.,  13.,  14.,  15.]]])]

In [190]:
np.vsplit(x, np.array([3, 6]))

[array([[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.]],
 
        [[  8.,   9.,  10.,  11.],
         [ 12.,  13.,  14.,  15.]]]),
 array([], shape=(0, 2, 4), dtype=float64),
 array([], shape=(0, 2, 4), dtype=float64)]

In [191]:
np.tile(x, 2)

array([[[  0.,   1.,   2.,   3.,   0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.,   4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.,   8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.,  12.,  13.,  14.,  15.]]])

In [192]:
np.tile(x,(4,1))

array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.],
        [  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.],
        [  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.],
        [  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.]]])

In [193]:
#repeating the arrays

In [194]:
np.repeat(x, 2)

array([  0.,   0.,   1.,   1.,   2.,   2.,   3.,   3.,   4.,   4.,   5.,
         5.,   6.,   6.,   7.,   7.,   8.,   8.,   9.,   9.,  10.,  10.,
        11.,  11.,  12.,  12.,  13.,  13.,  14.,  14.,  15.,  15.])

In [195]:
np.repeat(x, 3,axis=1)

array([[[  0.,   1.,   2.,   3.],
        [  0.,   1.,   2.,   3.],
        [  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  4.,   5.,   6.,   7.],
        [  4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.],
        [  8.,   9.,  10.,  11.],
        [  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.],
        [ 12.,  13.,  14.,  15.],
        [ 12.,  13.,  14.,  15.]]])

In [196]:
np.repeat(x, [1,2],axis=0)

array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.]],

       [[  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.]]])

In [197]:
np.repeat(x, [1,2],axis=1)

array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.],
        [ 12.,  13.,  14.,  15.]]])

In [198]:
np.delete(x, 1, 0)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]]])

In [199]:
np.delete(x, np.s_[::2], 1)

array([[[  4.,   5.,   6.,   7.]],

       [[ 12.,  13.,  14.,  15.]]])

In [200]:
np.delete(x, [1,3,5], None)

array([  0.,   2.,   4.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,
        14.,  15.])

In [201]:
#insert values in an array

In [202]:
np.insert(x, 1, 5)

array([  0.,   5.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,
        10.,  11.,  12.,  13.,  14.,  15.])

In [203]:
np.insert(x, 1, 5, axis=1)

array([[[  0.,   1.,   2.,   3.],
        [  5.,   5.,   5.,   5.],
        [  4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.],
        [  5.,   5.,   5.,   5.],
        [ 12.,  13.,  14.,  15.]]])

In [204]:
np.insert(x, [1], [[1],[2],[3]], axis=1)

array([[[  0.,   1.,   2.,   3.],
        [  1.,   1.,   1.,   1.],
        [  2.,   2.,   2.,   2.],
        [  3.,   3.,   3.,   3.],
        [  4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.],
        [  1.,   1.,   1.,   1.],
        [  2.,   2.,   2.,   2.],
        [  3.,   3.,   3.,   3.],
        [ 12.,  13.,  14.,  15.]]])

In [209]:
y = x.flatten()

In [210]:
np.insert(y, [2, 2], [5, 6])

array([  0.,   1.,   5.,   6.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,
         9.,  10.,  11.,  12.,  13.,  14.,  15.])

In [211]:
np.insert(y, slice(2, 4), [5, 6])

array([  0.,   1.,   5.,   2.,   6.,   3.,   4.,   5.,   6.,   7.,   8.,
         9.,  10.,  11.,  12.,  13.,  14.,  15.])

In [213]:
np.insert(y, [2, 2], [7.13, False])

array([  0.  ,   1.  ,   7.13,   0.  ,   2.  ,   3.  ,   4.  ,   5.  ,
         6.  ,   7.  ,   8.  ,   9.  ,  10.  ,  11.  ,  12.  ,  13.  ,
        14.  ,  15.  ])

In [214]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [219]:
np.append([[1, 2, 3], [4, 5, 6]], [7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
np.resize(x,(2,4))

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.]])

In [222]:
#getting the unique values from the numpy arrays

In [223]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [224]:
a = np.array([[1, 1], [2, 3]])

In [225]:
a

array([[1, 1],
       [2, 3]])

In [227]:
np.unique(a)

array([1, 2, 3])

In [228]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])


In [229]:
a

array([[1, 0, 0],
       [1, 0, 0],
       [2, 3, 4]])

In [230]:
np.unique(a, axis=0)

array([[1, 0, 0],
       [2, 3, 4]])

In [237]:
a = np.array(['a', 'b', 'b', 'c', 'a'])

In [238]:
a

array(['a', 'b', 'b', 'c', 'a'],
      dtype='<U1')

In [240]:
u, indices = np.unique(a, return_index=True)

In [241]:
u

array(['a', 'b', 'c'],
      dtype='<U1')

In [242]:
indices

array([0, 1, 3], dtype=int64)

In [243]:
a[indices]

array(['a', 'b', 'c'],
      dtype='<U1')

In [244]:
a = np.array([1, 2, 6, 4, 2, 3, 2])

In [245]:
a

array([1, 2, 6, 4, 2, 3, 2])

In [246]:
u, indices = np.unique(a, return_inverse=True)


In [247]:
u

array([1, 2, 3, 4, 6])

In [248]:
indices

array([0, 1, 4, 3, 1, 2, 1], dtype=int64)

In [249]:
u[indices]

array([1, 2, 6, 4, 2, 3, 2])