# Read data from file

In [48]:
#Construct an array from data in a text or binary file.A highly efficient way of reading binary data with a 
#known data-type, as well as parsing simply formatted text files. Data written using the tofile method can be 
#read using this function.

In [49]:
x

array([10,  2,  3])

In [50]:
import os

In [55]:
np.fromfile('C:/Datasets/College_Data')

array([  2.50400331e+262,   5.32000938e+232,   5.81323893e+170, ...,
         7.58796605e-096,   5.04659914e-038,   2.10613154e-052])

In [57]:
np.save('C:/Datasets/College_Data', x)

# numpy.fromfunction

In [58]:
#Construct an array by executing a function over each coordinate.

In [59]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]], dtype=bool)

In [60]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [61]:
#Create a new 1-dimensional array from an iterable object.

In [62]:
iterable = (x*x for x in range(5))

In [63]:
np.fromiter(iterable, float)

array([  0.,   1.,   4.,   9.,  16.])

In [64]:
#A new 1-D array initialized from text data in a string

In [65]:
np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

In [68]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

# Load data from a text file

In [69]:
from io import StringIO

In [70]:
c = StringIO("0 1\n2 3")

In [71]:
np.loadtxt(c)

array([[ 0.,  1.],
       [ 2.,  3.]])

In [72]:
d = StringIO("M 21 72\nF 35 58")

In [73]:
np.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'),
...                      'formats': ('S1', 'i4', 'f4')})

array([(b'M', 21,  72.), (b'F', 35,  58.)],
      dtype=[('gender', 'S1'), ('age', '<i4'), ('weight', '<f4')])

In [74]:
c = StringIO("1,0,2\n3,0,4")

In [75]:
x, y = np.loadtxt(c, delimiter=',', usecols=(0, 2), unpack=True)

In [76]:
x

array([ 1.,  3.])

In [77]:
y

array([ 2.,  4.])

In [79]:
# How to create create a record array from a (flat) list of arrays

In [80]:
x1=np.array([1,2,3,4])

In [81]:
x2=np.array(['a','dd','xyz','12'])

In [82]:
x3=np.array([1.1,2,3,4])

In [83]:
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')

In [84]:
print(r[1])

(2, 'dd', 2.0)


In [85]:
r.a

array([1, 2, 3, 4])