# Random number generation

In [132]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[ 0.17992539  0.77466986  0.40346943]
 [ 0.27872765  0.38668577  0.23248726]]


In [133]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.7234741   0.32885333 -0.60040597]
 [ 0.54863879  1.76326167 -0.97475272]
 [ 0.30910746  0.30583897  0.95082336]
 [-1.52208987  0.47583592  1.18738672]]


In [134]:
print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: [95 82 41 43 96 97 27 45 30 45]

Random integer matrix


In [135]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[11 12 83 23]
 [24 62 82 50]
 [ 2  3 83 76]
 [14 43 57 40]]

20 samples drawn from a dice throw: [6 3 2 3 3 2 1 2 4 2 5 2 2 1 4 1 4 3 3 2]


# Reshaping

In [136]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)


In [137]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [138]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [22  5  3 82 52 48 38  5  4 75 45 74 34 58 36 54 12 18 70 80 50 82 33 50 67
 33 75 32 17 35] 
 --------------------

b looks like
 -------------------- 
 [[[22  5  3 82 52]
  [48 38  5  4 75]
  [45 74 34 58 36]]

 [[54 12 18 70 80]
  [50 82 33 50 67]
  [33 75 32 17 35]]] 
 --------------------

c looks like
 -------------------- 
 [[22  5  3 82 52]
 [48 38  5  4 75]
 [45 74 34 58 36]
 [54 12 18 70 80]
 [50 82 33 50 67]
 [33 75 32 17 35]] 
 --------------------


In [139]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))



Vector of random integers
 -------------------------------------------------- 
 [64 93 37 58 33 61 30 19 68 25]

Here is the sorted vector
 -------------------------------------------------- 
 [19 25 30 33 37 58 61 64 68 93]


In [140]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[23 72  6 36 36]
 [61 15 43 94 70]
 [30 77 75 85 76]
 [48 46 34 26 68]
 [16 84 33 53 57]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 6 23 36 36 72]
 [15 43 61 70 94]
 [30 75 76 77 85]
 [26 34 46 48 68]
 [16 33 53 57 84]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[16 15  6 26 36]
 [23 46 33 36 57]
 [30 72 34 53 68]
 [48 77 43 85 70]
 [61 84 75 94 76]]


In [141]:
print("Max of a:", a.max())
print("Max of b:", b.max())


Max of a: 82
Max of b: 82


In [142]:
print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: 3
Max of b location: 3
Max of c location: 3


# Indexing and slicing

In [143]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [144]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [145]:
print("Elements from 3rd to 5th index are:", arr[3:6])


Elements from 3rd to 5th index are: [3 4 5]


In [146]:
print("Elements up to 4th index are:", arr[:4])


Elements up to 4th index are: [0 1 2 3]


In [147]:
print("Elements from last backwards are:", arr[-1::-1])


Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]


In [148]:
print("3 Elements from last backwards are:", arr[-1:-6:-2])


3 Elements from last backwards are: [10  8  6]


In [149]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [150]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [151]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


Matrix of random 2-digit numbers
--------------------------------
 [[47 77 92 69 39]
 [39 64 49 17 53]
 [75 38 48 99 95]]


In [152]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])



Double bracket indexing
------------------------
Element in row index 1 and column index 2: 49


In [153]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 49

Row or column extract
----------------------


In [154]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [75 38 48 99 95]
Entire column at index 3: [69 17 99]


In [155]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[17 53]
 [99 95]]


In [156]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[77 69]
 [64 17]]
