# basic stats

In [252]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[9 5 9]
 [6 1 8]
 [8 4 3]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[7 3 2]
 [1 4 2]
 [9 8 8]]


In [253]:
print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))



Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 53

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [23 10 20]


In [254]:
print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=1))



Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [23 15 15]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [405  48  96]


In [255]:
print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))



Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [63 96 32]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.88888888889


In [256]:
print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))



Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2.68512132747


In [257]:
mat1 = np.array(ri(1,100,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)



Modified matrix of random numbers from 1 to 99
 -------------------------------------------------- 
 [[41 34 94]
 [79 20 23]
 [61  4 90]]


In [258]:
print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))



Standard deviation of all numbers in the modified matrix, a larger number
 -------------------------------------------------------------------------------- 
 30.8728975393


In [259]:
print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))



Variance of all numbers in the modified matrix, a larger number
 -------------------------------------------------------------------------------- 
 953.135802469


In [260]:
print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



Median of all numbers in the modified matrix
 ------------------------------------------------------------ 
 41.0


In [261]:
mat2 = np.array(ri(1,100,50)).reshape(10,5)


In [262]:
print("\nModified matrix of 50 random numbers from 1 to 99\n","-"*50,"\n",mat2)



Modified matrix of 50 random numbers from 1 to 99
 -------------------------------------------------- 
 [[41 40 44 13 41]
 [39 67 47 34 99]
 [17 13  3 58 92]
 [14 38 35 29 89]
 [ 5 97 84 10 41]
 [22 49  9 18 15]
 [61 17  6 68 69]
 [75 52 55 92 31]
 [60 71 75 43 11]
 [29  5 11 27 77]]


In [263]:
print("\nStandard deviation along the columns in the modified matrix\n","-"*60,"\n",np.std(mat2,axis=0))



Standard deviation along the columns in the modified matrix
 ------------------------------------------------------------ 
 [ 21.92281916  27.22296824  27.761304    25.00719896  31.02015474]


In [264]:
mat1 = np.array(ri(1,100,20)).reshape(4,5)


In [265]:
print("\nModified matrix of random numbers from 1 to 49\n","-"*50,"\n",mat1)



Modified matrix of random numbers from 1 to 49
 -------------------------------------------------- 
 [[37 72 74 57  7]
 [93 64  9 80 58]
 [28 13 16 87 55]
 [56 14 38 21 69]]


In [266]:
print("\nFlattened and sorted matrix (as vector)\n","-"*50,"\n",np.sort(mat1.reshape(1,20)))



Flattened and sorted matrix (as vector)
 -------------------------------------------------- 
 [[ 7  9 13 14 16 21 28 37 38 55 56 57 58 64 69 72 74 80 87 93]]


In [267]:
print("\n50th percentile of all numbers in the modified matrix\n","-"*60,"\n",np.percentile(mat1,50))



50th percentile of all numbers in the modified matrix
 ------------------------------------------------------------ 
 55.5


In [268]:
print("\n90th percentile of all numbers in the modified matrix\n","-"*60,"\n",np.percentile(mat1,90))


90th percentile of all numbers in the modified matrix
 ------------------------------------------------------------ 
 80.7
