# Numpy Array

In [2]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
#Upcasting:

In [4]:
np.array([1, 2, 3.0])

array([ 1.,  2.,  3.])

In [5]:
#two dimensions

In [6]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [7]:
#Minimum dimensions 2:

In [8]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [9]:
#dtype

In [10]:
 np.array([1, 2, 3], dtype=complex)

array([ 1.+0.j,  2.+0.j,  3.+0.j])

In [11]:
#Data-type consisting of more than one element:

In [12]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])

In [13]:
x['a']

array([1, 3])

In [14]:
#Creating an array from sub-classes:

In [15]:
np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [16]:
np.array(np.mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [17]:
#Convert the input to an array.

In [18]:
#Convert a list into an array:

In [21]:
 a = [1, 2]

In [22]:
np.asarray(a)

array([1, 2])

In [23]:
a = np.array([1, 2]) #Existing arrays are not copied

In [24]:
np.asarray(a) is a

True

In [25]:
#If dtype is set, array is copied only if dtype does not match:

In [26]:
a = np.array([1, 2], dtype=np.float32)

In [27]:
np.asarray(a, dtype=np.float32) is a

True

In [28]:
np.asarray(a, dtype=np.float64) is a

False

In [29]:
# ndarray subclasses are not passed through

In [30]:
issubclass(np.matrix, np.ndarray)

True

In [31]:
a = np.matrix([[1, 2]])

In [32]:
np.asarray(a) is a

False

In [33]:
np.asanyarray(a) is a

True

# numpy.asanyarray

In [35]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [36]:
a = np.matrix([1, 2])

In [37]:
np.asanyarray(a) is a

True

In [39]:
np.array(a, copy=True)  

array([[1, 2]])

In [40]:
#Create an array x, with a reference y and a copy z:

In [41]:
x = np.array([1, 2, 3])

In [42]:
y = x

In [43]:
z = np.copy(x)

In [44]:
#when we modify x, y changes, but not z

In [45]:
x[0] = 10

In [46]:
x[0] == y[0]

True

In [47]:
x[0] == z[0]

False